In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV, train_test_split
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import joblib

In [2]:
df = pd.read_csv("C:/Manasi/NMIMS/Manasi/Capstone Project/Agriculture/Datasets/agri.csv")
df.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,Andhra Pradesh,East Godavari,Ravulapelem,Banana,Chakkarakeli(Red),Large,25-10-24,2100.0,2600.0,2400.0
1,Andhra Pradesh,East Godavari,Ravulapelem,Banana,Karpura,Large,25-10-24,1200.0,2400.0,1800.0
2,Assam,Barpeta,Barpeta Road,Green Chilli,Green Chilly,Local,25-10-24,8000.0,9000.0,9000.0
3,Assam,Goalpara,Lakhipur,Pumpkin,Pumpkin,Local,25-10-24,1500.0,2000.0,2000.0
4,Assam,Goalpara,Lakhipur,Tomato,Tomato,Local,25-10-24,3000.0,3500.0,3400.0

In [3]:
df = df.rename(columns={
    'Min_x0020_Price': 'Min_Price',
    'Max_x0020_Price': 'Max_Price',
    'Modal_x0020_Price': 'Modal_Price'
})

df.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price
0,Andhra Pradesh,East Godavari,Ravulapelem,Banana,Chakkarakeli(Red),Large,25-10-24,2100.0,2600.0,2400.0
1,Andhra Pradesh,East Godavari,Ravulapelem,Banana,Karpura,Large,25-10-24,1200.0,2400.0,1800.0
2,Assam,Barpeta,Barpeta Road,Green Chilli,Green Chilly,Local,25-10-24,8000.0,9000.0,9000.0
3,Assam,Goalpara,Lakhipur,Pumpkin,Pumpkin,Local,25-10-24,1500.0,2000.0,2000.0
4,Assam,Goalpara,Lakhipur,Tomato,Tomato,Local,25-10-24,3000.0,3500.0,3400.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11274 entries, 0 to 11273
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   State         11274 non-null  object
 1   District      11274 non-null  object
 2   Market        11274 non-null  object
 3   Commodity     11274 non-null  object
 4   Variety       11274 non-null  object
 5   Grade         11274 non-null  object
 6   Arrival_Date  11274 non-null  object
 7   Min_Price     11274 non-null  float64
 8   Max_Price     11274 non-null  float64
 9   Modal_Price   11274 non-null  float64
dtypes: float64(3), object(7)
memory usage: 880.9+ KB

In [5]:
df['Arrival_Date'] = pd.to_datetime(df['Arrival_Date'], format='%d-%m-%y')

In [6]:
for column in df.columns:
    print(f"Unique values in '{column}':")
    print(df[column].unique(), "\n")

Unique values in 'State':
['Andhra Pradesh' 'Assam' 'Bihar' 'Chattisgarh' 'Gujarat' 'Haryana'
 'Himachal Pradesh' 'Jammu and Kashmir' 'Karnataka' 'Kerala'
 'Madhya Pradesh' 'Maharashtra' 'Manipur' 'Meghalaya' 'Nagaland' 'Odisha'
 'Punjab' 'Rajasthan' 'Tamil Nadu' 'Telangana' 'Tripura' 'Uttar Pradesh'
 'Uttrakhand' 'West Bengal' 'Goa']

Unique values in 'District':
['East Godavari' 'Barpeta' 'Goalpara' 'Kamrup' 'Karbi Anglong' 'MORIGAON'
 'Nalbari' 'Sibsagar' 'Sonitpur' 'Buxar' 'Jehanabad' 'Rohtas'
 'Balodabazar' 'Bastar' 'Dhamtari' 'Durg' 'Jashpur' 'Kanker' 'Korba'
 'Mahasamund' 'Raigarh' 'Rajnandgaon' 'Surajpur' 'Amreli' 'Anand'
 'Bharuch' 'Dahod' 'Gir Somnath' 'Junagarh' 'Kheda' 'Navsari' 'Rajkot'
 'Sabarkantha' 'Surendranagar' 'Vadodara(Baroda)' 'Ambala' 'Bhiwani'
 'Fatehabad' 'Gurgaon' 'Hissar' 'Jind' 'Kurukshetra'
 'Mahendragarh-Narnaul' 'Mewat' 'Panipat' 'Rewari' 'Sirsa' 'Sonipat'
 'Yamuna Nagar' 'Chamba' 'Hamirpur' 'Kangra' 'Kullu' 'Mandi' 'Anantnag'
 'Badgam' 'Jammu' 'Kathua' 'Kupwara' 'Rajouri' 'Udhampur' 'Bangalore'
 'Chikmagalur' 'Davangere' 'Dharwad' 'Alappuzha' 'Ernakulam' 'Idukki'
 'Kannur' 'Kollam' 'Kottayam' 'Kozhikode(Calicut)' 'Malappuram' 'Palakad'
 'Pathanamthitta' 'Thirssur' 'Thiruvananthapuram' 'Wayanad' 'Alirajpur'
 'Badwani' 'Dhar' 'Dindori' 'Harda' 'Indore' 'Jhabua' 'Katni' 'Raisen'
 'Ratlam' 'Satna' 'Seoni' 'Shivpuri' 'Ujjain' 'Umariya' 'Ahmednagar'
 'Mumbai' 'Nagpur' 'Pune' 'Sangli' 'Satara' 'Thane' 'Bishnupur'
 'Imphal East' 'East Khasi Hills' 'Tsemenyu' 'Bargarh' 'Boudh' 'Dhenkanal'
 'Gajapati' 'Jagatsinghpur' 'Jharsuguda' 'Khurda' 'Koraput' 'Nuapada'
 'Rayagada' 'Fazilka' 'Gurdaspur' 'Hoshiarpur' 'Jalandhar' 'Ludhiana'
 'Moga' 'Mohali' 'Ropar (Rupnagar)' 'Tarntaran' ' Jhunjhunu' 'Ajmer'
 'Bikaner' 'Dausa' 'Ganganagar' 'Hanumangarh' 'Jaipur Rural' 'Jalore'
 'Jodhpur' 'Jodhpur Rural' 'Ariyalur' 'Chengalpattu' 'Coimbatore'
 'Cuddalore' 'Dharmapuri' 'Dindigul' 'Erode' 'Kallakuruchi' 'Kancheepuram'
 'Karur' 'Krishnagiri' 'Madurai' 'Nagapattinam'
 'Nagercoil (Kannyiakumari)' 'Namakkal' 'Perambalur' 'Pudukkottai'
 'Ramanathapuram' 'Ranipet' 'Salem' 'Sivaganga' 'Tenkasi' 'Thanjavur'
 'The Nilgiris' 'Theni' 'Thiruchirappalli' 'Thirunelveli' 'Thirupathur'
 'Thirupur' 'Thiruvannamalai' 'Thiruvarur' 'Thiruvellore' 'Tuticorin'
 'Vellore' 'Villupuram' 'Virudhunagar' 'Karimnagar' 'Khammam'
 'Mahbubnagar' 'Ranga Reddy' 'Warangal' 'Gomati' 'Khowai' 'North Tripura'
 'South District' 'Aligarh' 'Amethi' 'Amroha' 'Ayodhya' 'Badaun' 'Baghpat'
 'Ballia' 'Balrampur' 'Banda' 'Bijnor' 'Bulandshahar' 'Etawah'
 'Farukhabad' 'Fatehpur' 'Firozabad' 'Gonda' 'Gorakhpur' 'Hathras'
 'Jalaun (Orai)' 'Jaunpur' 'Jhansi' 'Khiri (Lakhimpur)' 'Lakhimpur'
 'Lucknow' 'Maharajganj' 'Mainpuri' 'Mathura' 'Mau(Maunathbhanjan)'
 'Pillibhit' 'Pratapgarh' 'Raebarelli' 'Rampur' 'Saharanpur' 'Sambhal'
 'Shahjahanpur' 'Shamli' 'Siddharth Nagar' 'Unnao' 'Dehradoon'
 'Garhwal (Pauri)' 'Haridwar' 'Nanital' 'UdhamSinghNagar' 'Bankura'
 'Birbhum' 'Coochbehar' 'Dakshin Dinajpur' 'Kalimpong' 'Malda'
 'Medinipur(E)' 'Medinipur(W)' 'Murshidabad' 'Paschim Bardhaman'
 'Anantapur' 'Chittor' 'Kurnool' 'Kishanganj' 'Dantewada' 'North Goa'
 'South Goa' 'Ahmedabad' 'Chhota Udaipur' 'Valsad' 'Srinagar'
 'Chamrajnagar' 'Kolar' 'Raichur' 'Guna' 'Jabalpur' 'Mandla' 'Mandsaur'
 'Narsinghpur' 'Rajgarh' 'Sagar' 'Sehore' 'Sidhi' 'Singroli' 'Ratnagiri'
 'Mayurbhanja' 'Puri' 'Sundergarh' 'Sangrur' 'Beawar' 'Nalgonda'
 'Bareilly' 'Etah' 'Prayagraj' 'Sant Kabir Nagar' 'Champawat'
 'North 24 Parganas' 'Araria' 'Patna' 'Sheikhpura' 'Vaishali' 'Janjgir'
 'Narayanpur' 'Raipur' 'Banaskanth' 'Kachchh' 'Narmada' 'Patan' 'Surat'
 'Koppal' 'Mandya' 'Bhopal' 'Chhatarpur' 'Damoh' 'Gwalior' 'Khargone'
 'Vidisha' 'Jalgaon' 'Balasore' 'Bhatinda' 'Churu' 'Dungarpur' 'Deoria'
 'Hardoi' 'Bijapur' 'Panchkula' 'Burhanpur' 'Dewas' 'Khandwa' 'Shajapur'
 'Bolangir' 'Amritsar' 'Faridkot' 'Kotputli- Behror' 'Lalitpur' 'Bhojpur'
 'Madhubani' 'Gandhinagar' 'Madikeri(Kodagu)' 'Anupur' 'Betul' 'Datia'
 'Tikamgarh' 'Gadchiroli' 'Raigad' 'Sikar' 'Medak']

Unique values in 'Market':
['Ravulapelem' 'Barpeta Road' 'Lakhipur' 'Pamohi(Garchuk)' 'Manja'
 'Jagiroad Dry Fish Market' 'Nalbari' 'Sibsagar' 'Dhekiajuli' 'Brahmpur'
 'Jehanabad' 'Sasaram' 'Bhatgaon' 'Kasdol' 'Sarsiwan' 'Karpawand' 'Boraee'
 'Gattasilli' 'Durg' 'Pathalgaon' 'Bhanupratappur' 'Lakhanpuri'
 'Narharpur' 'Katghora' 'Sarayapali' 'Raigarh' 'Chhuria' 'Gandai'
 'Rajnandgaon' 'Surajpur' 'Babra' 'Bagasara' 'Damnagar' 'Rajula'
 'Khambhat(Veg Yard Khambhat)' 'Bharuch' 'Jambusar(Kaavi)' 'Dahod'
 'Dahod(Veg. Market)' 'Una' 'Mangrol' 'Nadiyad(Chaklasi)'
 'Nadiyad(Piplag)' 'Navsari' 'Gondal(Veg.market Gondal)'
 'Jetpur(Dist.Rajkot)' 'Rajkot' 'Rajkot(Veg.Sub Yard)' 'Modasa(Tintoi)'
 'Vadali' 'Dasada Patadi' 'Vadhvan' 'Padra' 'Naraingarh' 'Loharu' 'Jakhal'
 'Gurgaon' 'Barwala(Hisar)' 'Hansi' 'Narwana' 'Ladwa' 'Pehowa' 'Shahabad'
 'Narnaul' 'Tauru' 'Panipat' 'Rewari' 'kalanwali' 'Gohana' 'Chhachrauli'
 'Chamba' 'Hamirpur' 'Hamirpur(Nadaun)' 'Dharamshala' 'Kangra'
 'Kangra(Baijnath)' 'Kangra(Jaisinghpur)' 'Kangra(Nagrota Bagwan)'
 'Palampur' 'Bhuntar' 'Kullu' 'Mandi(Mandi)' 'Kulgam'
 'Zaloosa-Chararishrief (F&V)' 'Narwal Jammu (F&V)' 'Kathua'
 'Bumhama-Kupwara (F&V)' 'Rajouri (F&V)' 'Udhampur' 'Ramanagara'
 'Chikkamagalore' 'Harappana Halli' 'Kalagategi' 'Aroor' 'Chengannur'
 'Harippad' 'Kayamkulam' 'Angamaly' 'North Paravur' 'Thrippunithura'
 'Thodupuzha' 'Kannur' 'Thalasserry' 'Chathanoor' 'Athirampuzha'
 'Ettumanoor' 'Kanjirappally' 'Kottayam' 'Kuriem  VFPCK' 'Kuruppanthura'
 'Mutholy  VFPCK' 'Pala' 'Pampady' 'Thalayolaparambu' 'Thottuva  VFPCK'
 'Kallachi' 'Mukkom' 'Palayam' 'Perambra' 'Thamarassery' 'Kodakkad  VFPCK'
 'Kottakkal' 'Koduvayoor' 'Kollengode' 'Palakkad' 'Pattambi' 'Kuttoor'
 'Mezhuveli  VFPCK' 'Chavakkad' 'Chelakkara' 'Marottichal  VFPCK'
 'Anyara(EEC)' 'Kovilnada  VFPCK' 'Neyyatinkara' 'Parassala' 'Pothencode'
 'Kalpetta' 'Manathavady' 'Pulpally' 'Alirajpur' 'Sendhwa' 'Dhamnod'
 'Dhar' 'Kukshi' 'Dindori' 'Gorakhpur' 'Sirali(F&V)' 'Indore' 'Petlawad'
 'Katni' 'Raisen' 'Jaora' 'Sailana' 'Satna' 'Seoni' 'Kolaras' 'Mahidpur'
 'Umariya' 'Karjat' 'Shrirampur' 'Mumbai' 'Kalmeshwar' 'Khed(Chakan)'
 'Pune' 'Pune(Khadiki)' 'Pune(Moshi)' 'Pune(Pimpri)' 'Islampur' 'Vai'
 'Kalyan' 'Murbad' 'Bishenpur' 'Lamlong Bazaar' 'Shillong' 'Tsemenyu'
 'Padampur' 'Sohela' 'Boudh' 'Hindol' 'Kamakhyanagar' 'Parlakhemundi'
 'Rahama' 'Jharsuguda' 'Balugaon' 'Jatni' 'Koraput' 'Koraput(Semilguda)'
 'Khariar' 'Khariar Road' 'Gunpur' 'Rayagada(Muniguda)' 'Jalalabad'
 'Kalanaur' 'Garh Shankar' 'GarhShankar (Kotfatuhi)' 'Mukerian'
 'Mukerian(Talwara)' 'Tanda Urmur' 'Jalandhar City(Jalandhar)' 'Mehatpur'
 'Phillaur(Apra Mandi)' 'Doraha' 'Ludhiana' 'Ludhiana(Salem Tabri)'
 'Sahnewal' 'Sidhwan Bet' 'Kot ise Khan' 'Nihal Singh Wala' 'Dera Bassi'
 'Kharar' 'Kurali' 'Chamkaur Sahib' 'Ropar' 'Patti' 'Tarantaran'
 'Nawalgarh' 'Surajgarh' 'Madanganj Kishangarh' 'Bikaner (F&V)' 'Lalsot'
 'Mandawari' 'Sriganganagar (F&V)' 'Suratgarh' 'Rawatsar' 'Bassi' 'Jalore'
 'Jodhpur (F&V)' 'Jodhpur(F&V)(Paota)' 'Ositan Mathania'
 'Ariyalur(Uzhavar Sandhai)' 'Jeyankondam (Uzhavar Sandhai )'
 'Chengalpet(Uzhavar Sandhai )' 'Jameenrayapettai(Uzhavar Sandhai )'
 'Madhuranthagam(Uzhavar Sandhai )' 'Medavakkam(Uzhavar Sandhai )'
 'Nanganallur(Uzhavar Sandhai )' 'Pallavaram(Uzhavar Sandhai )'
 'Thirukalukundram(Uzhavar Sandhai )' 'Kurichi(Uzhavar Sandhai )'
 'Mettupalayam(Uzhavar Sandhai )' 'Pollachi(Uzhavar Sandhai )'
 'RSPuram(Uzhavar Sandhai )' 'Singanallur(Uzhavar Sandhai )'
 'Sulur(Uzhavar Sandhai )' 'Sundarapuram(Uzhavar Sandhai )' 'Udumalpet'
 'Vadavalli(Uzhavar Sandhai )' 'Chidambaram(Uzhavar Sandhai )'
 'Cuddalore(Uzhavar Sandhai )' 'Panruti(Uzhavar Sandhai )'
 'Viruthachalam(Uzhavar Sandhai )' 'AJattihalli(Uzhavar Sandhai )'
 'Dharmapuri(Uzhavar Sandhai )' 'Harur(Uzhavar Sandhai )'
 'Palacode(Uzhavar Sandhai )' 'Pennagaram(Uzhavar Sandhai )'
 'Chinnalapatti(Uzhavar Sandhai )' 'Dindigul(Uzhavar Sandhai )'
 'Palani(Uzhavar Sandhai )' 'Vedasanthur(Uzhavar Sandhai )'
 'Gobichettipalayam(Uzhavar Sandhai )' 'Periyar Nagar(Uzhavar Sandhai )'
 'Perundurai(Uzhavar Sandhai )' 'Sampath Nagar(Uzhavar Sandhai )'
 'Sathiyamagalam(Uzhavar Sandhai )' 'Thalavadi(Uzhavar Sandhai )'
 'Kallakurichi(Uzhavar Sandhai )' 'Sankarapuram(Uzhavar Sandhai )'
 'Kundrathur(Uzhavar Sandhai )' 'Padappai(Uzhavar Sandhai )' 'Tiruttani'
 'Karur(Uzhavar Sandhai )' 'Kulithalai(Uzhavar Sandhai )'
 'Pallapatti (Uzhavar Sandhai )' 'Velayuthampalayam(Uzhavar Sandhai )'
 'Avallapalli(Uzhavar Sandhai )' 'Denkanikottai(Uzhavar Sandhai )'
 'Hosur(Uzhavar Sandhai )' 'Kaveripattinam(Uzhavar Sandhai )'
 'Krishnagiri(Uzhavar Sandhai )' 'Anaiyur(Uzhavar Sandhai )'
 'Anna nagar(Uzhavar Sandhai )' 'Chokkikulam(Uzhavar Sandhai )'
 'Melur(Uzhavar Sandhai )' 'Palanganatham(Uzhavar Sandhai )'
 'Thirumangalam(Uzhavar Sandhai )' 'Usilampatty'
 'Mayiladuthurai(Uzhavar Sandhai )' 'Nagapattinam(Uzhavar Sandhai )'
 'Sirkali(Uzhavar Sandhai )' 'Myladi(Uzhavar Sandhai )' 'Vadaseri'
 'Kumarapalayam(Uzhavar Sandhai )' 'Mohanur(Uzhavar Sandhai )'
 'Namakkal(Uzhavar Sandhai )' 'Paramathivelur(Uzhavar Sandhai )'
 'Rasipuram(Uzhavar Sandhai )' 'Tiruchengode'
 'Perambalur(Uzhavar Sandhai )' 'Alangudi(Uzhavar Sandhai )'
 'Aranthangi(Uzhavar Sandhai )' 'Gandarvakottai(Uzhavar Sandhai )'
 'Karambakkudi(Uzhavar Sandhai )' 'Pudukottai(Uzhavar Sandhai )'
 'Viralimalai(Uzhavar Sandhai )' 'Paramakudi'
 'Paramakudi(Uzhavar Sandhai )' 'Ramanathapuram(Uzhavar Sandhai )'
 'Arcot(Uzhavar Sandhai )' 'Ranipettai(Uzhavar Sandhai )'
 'Ammapet(Uzhavar Sandhai )' 'Athur(Uzhavar Sandhai )'
 'Attayampatti(Uzhavar Sandhai )' 'Edapadi (Uzhavar Sandhai )'
 'Elampillai(Uzhavar Sandhai )' 'Hasthampatti(Uzhavar Sandhai )'
 'Jalagandapuram(Uzhavar Sandhai )' 'Mettur(Uzhavar Sandhai )'
 'Sooramangalam(Uzhavar Sandhai )' 'Thammampatti (Uzhavar Sandhai )'
 'Thathakapatti(Uzhavar Sandhai )' 'Devakottai (Uzhavar Sandhai )'
 'Karaikudi(Uzhavar Sandhai )' 'Singampunari(Uzhavar Sandhai )'
 'Sivagangai (Uzhavar Sandhai )' 'Tirupatthur(Uzhavar Sandhai )'
 'Sankarankoil(Uzhavar Sandhai )' 'Tenkasi(Uzhavar Sandhai )'
 'Kumbakonam (Uzhavar Sandhai )' 'Papanasam(Uzhavar Sandhai )'
 'Pattukottai(Uzhavar Sandhai )' 'Thanjavur(Uzhavar Sandhai )'
 'Coonoor(Uzhavar Sandhai )' 'Gudalur(Uzhavar Sandhai )'
 'Udhagamandalam(Uzhavar Sandhai )' 'Andipatti(Uzhavar Sandhai )'
 'Bodinayakanur(Uzhavar Sandhai )' 'Chinnamanur(Uzhavar Sandhai )'
 'Devaram(Uzhavar Sandhai )' 'Kambam(Uzhavar Sandhai )'
 'Periyakulam(Uzhavar Sandhai )' 'Theni(Uzhavar Sandhai )'
 'Lalgudi(Uzhavar Sandhai )' 'Manachanallur(Uzhavar Sandhai )'
 'Manapparai(Uzhavar Sandhai )' 'Musiri(Uzhavar Sandhai )' 'Thuraiyur'
 'Ambasamudram(Uzhavar Sandhai )' 'Kandiyaperi(Uzhavar Sandhai )'
 'Melapalayam(Uzhavar Sandhai )' 'NGO Colony(Uzhavar Sandhai )'
 'Palayamkottai(Uzhavar Sandhai )' 'Natrampalli(Uzhavar Sandhai )'
 'Vaniyampadi(Uzhavar Sandhai )' 'Dharapuram(Uzhavar Sandhai )'
 'Kangayam(Uzhavar Sandhai )' 'Palladam(Uzhavar Sandhai )'
 'Tiruppur (North) (Uzhavar Sandhai )'
 'Tiruppur (South) (Uzhavar Sandhai )' 'Arani(Uzhavar Sandhai )'
 'Chengam(Uzhavar Sandhai )' 'Cheyyar(Uzhavar Sandhai )'
 'Keelpennathur(Uzhavar Sandhai )' 'Polur(Uzhavar Sandhai )'
 'Tamarainagar(Uzhavar Sandhai )' 'Tiruvannamalai(Uzhavar Sandhai )'
 'Vandavasi' 'Mannargudi I(Uzhavar Sandhai )'
 'Mannargudi II(Uzhavar Sandhai )' 'Muthupettai(Uzhavar Sandhai )'
 'Needamangalam(Uzhavar Sandhai )' 'Tiruthuraipoondi(Uzhavar Sandhai )'
 'Tiruvarur(Uzhavar Sandhai )' 'Valangaiman'
 'Naravarikuppam(Uzhavar Sandhai )' 'Paruthipattu(Uzhavar Sandhai )'
 'Tiruvallur(Uzhavar Sandhai )' 'Kovilpatti(Uzhavar Sandhai )'
 'Tuticorin(Uzhavar Sandhai )' 'Ammoor' 'Gudiyatham(Uzhavar Sandhai )'
 'Kahithapattarai(Uzhavar Sandhai )' 'Katpadi (Uzhavar Sandhai )'
 'Thirupathur' 'Vellore' 'Gingee' 'Gingee(Uzhavar Sandhai )' 'Tindivanam'
 'Ulundurpettai' 'Aruppukottai(Uzhavar Sandhai )'
 'Kariyapatti(Uzhavar Sandhai )' 'Rajapalayam(Uzhavar Sandhai )'
 'Sathur(Uzhavar Sandhai )' 'Sivakasi(Uzhavar Sandhai )'
 'Srivilliputhur(Uzhavar Sandhai )' 'Thalavaipuram(Uzhavar Sandhai )'
 'Virudhunagar(Uzhavar Sandhai )' 'Sircilla' 'Kothagudem' 'Wyra'
 'Yellandu' 'Nagarkurnool' 'Kukatpally(Rythu Bazar)'
 'Mehndipatnam(Rythu Bazar)' 'Warangal' 'Nutanbazar' 'Teliamura' 'Dasda'
 'Barpathari' 'Aligarh' 'Atrauli' 'Sultanpur' 'Amroha' 'Faizabad'
 'Babrala' 'Badayoun' 'Shahaswan' 'Visoli' 'Khekda' 'Ballia' 'Tulsipur'
 'Banda' 'Chaandpur' 'Anoop Shahar' 'Gulavati' 'Sikanderabad' 'Sikarpur'
 'Jasvantnagar' 'Kamlaganj' 'Fatehpur' 'Jahanabad' 'Khaga' 'Kishunpur'
 'Tundla' 'Nawabganj' 'Chorichora' 'Shadabad' 'Jalaun' 'Jaunpur'
 'Mugrabaadshahpur' 'Jhansi' 'Maigalganj' 'Lakhimpur' 'Banthara'
 'Anandnagar' 'Gadaura' 'Nautnava' 'Ghiraur' 'Mainpuri' 'Kosikalan'
 'Doharighat' 'Kopaganj' 'Puranpur' 'Pratapgarh' 'Bachranwa' 'Raibareilly'
 'Salon' 'Rampur' 'Chutmalpur' 'Bhehjoi' 'Muradabad' 'Puwaha'
 'Shahjahanpur' 'Kairana' 'Thanabhavan' 'Naugarh' 'Bangarmau' 'Rishikesh'
 'Vikasnagar' 'Kotadwara' 'Haridwar Union' 'Manglaur' 'Ramnagar' 'Bazpur'
 'Gadarpur' 'Jaspur(UC)' 'Rudrapur' 'Bankura Sadar' 'Birbhum' 'Dinhata'
 'Mekhliganj' 'Gangarampur(Dakshin Dinajpur)' 'Kalimpong' 'Samsi'
 'Egra/contai' 'Kolaghat' 'Garbeta(Medinipur)' 'Medinipur(West)' 'Kandi'
 'Asansol' 'Durgapur' 'Kadiri' 'Chittoor' 'Kalikiri' 'Karapa' 'Pattikonda'
 'Brahmaputra Private Market' 'Bahadurganj' 'Kochas (Balthari)' 'Bastar'
 'Gidam' 'Nagari' 'Kotba' 'Sambalpur' 'Dongargaon' 'Valpol' 'Curchorem'
 'Viramgam' 'Jambusar' 'Kalediya' 'Modasar        ' 'Davgadbaria(Piplod)'
 'Dhoraji' 'Modasa' 'Chikli(Khorgam)' 'Mullana(saha)' 'Uklana' 'Punhana'
 'Kullu(Chauri Bihal)' 'Akhnoor' 'Ganderbal' 'Chamaraj Nagar' 'Malur'
 'Lingasugur' 'Cherthala' 'Kottarakkara' 'Kattampak  VFPCK'
 'Vellannur  VFPCK' 'Kalanjoor  VFPCK' 'Vamanapuram' 'Anjad' 'Badwani'
 'Badwani(F&V)' 'Badnawar' 'Manawar' 'Binaganj' 'Harda' 'Paatan' 'Sehora'
 'Jhabua' 'Mandla' 'Piplya' 'Gadarwada' 'Tendukheda' 'Pachaur' 'Sagar'
 'Sehore' 'Ghansour' 'Keolari' 'Khanyadhana' 'Sidhi' 'Singroli'
 'Ratnagiri (Nachane)' 'Palghar' 'Attabira' 'Khunthabandha' 'Karanjia'
 'Dumal' 'Sargipali' 'Ahmedgarh' 'Beawar' 'Bajju' 'Sangriya'
 'Jodhpur (Grain)' 'Guduvancheri(Uzhavar Sandhai )'
 'Kancheepuram(Uzhavar Sandhai )' 'Ambattur(Uzhavar Sandhai )'
 'Perambakkam(Uzhavar Sandhai )' 'Husnabad' 'Manthani' 'Burgampadu'
 'Dammapet' 'Bhongir' 'Devarakonda' 'Miryalaguda' 'Ramannapet'
 'Hanmarkonda(Rythu Bazar)' 'Bagpat' 'Rasda' 'Anwala' 'Aliganj' 'Sirsa'
 'Lalganj' 'Sambhal' 'Khalilabad' 'Tanakpur' 'Roorkee' 'Kicchha'
 'Indus(Bankura Sadar)' 'Bolpur' 'Tamluk (Medinipur E)' 'Barasat'
 'Mulakalacheruvu' 'Rajahmundry' 'Sampara' 'Forbesganj' 'Danapur'
 'Barbigha' 'Jaitipir Mandi, Lalganj block' 'Belarbahara' 'Belargaon'
 'Champa' 'Narayanpur' 'Abhanpur' 'Vav' 'Devgadhbaria' 'Limkheda' 'Rapar'
 'Nadiad' 'Rajpipla' 'Sami' 'Mahuva(Anaval)' 'Chotila' 'Valsad' 'Mullana'
 'Yalburga' 'Srirangapattana' 'Muriyad  VFPCK' 'Jobat' 'Khetia' 'Bhopal'
 'Naugaon' 'Javera' 'Dabra' 'Khargone' 'Mandsaur' 'Shamgarh' 'Ratlam'
 'Bina' 'Nasrullaganj' 'Ganjbasoda' 'Rahuri' 'Jalgaon(Masawat)' 'Nilagiri'
 'Jagatsinghpur' 'Bhagta Bhai Ka' 'Rampuraphul(Nabha Mandi)'
 'Jalandhar City' 'Sidhwan Bet (Lodhiwala)' 'Sadulpur' 'Dungarpur'
 'Dindigul' 'Kalavai' 'Huzzurabad' 'Achampet' 'Huzurnagar(Matampally)'
 'Thungathurthy' 'Dataganj' 'Devariya' 'Sandi' 'Sikandraraau' 'Ait'
 'Chirgaon' 'Bewar' 'Vilaspur' 'Lakshar' 'Kasimbazar' 'Natwar' 'Shekhpura'
 'Bijapur' 'Charama' 'Korar' 'Bodeliu' 'Hadad    '
 'New Grain Market , Panchkula' 'Parakkodu' 'Karuvannur VFPCK'
 'Anjad(F&V)' 'Burhanpur' 'Dewas' 'Shahpura(Jabalpur)' 'Khandwa' 'Badwaha'
 'Sanawad' 'Chhpara' 'Nalkehda' 'Shajapur' 'Tarana' 'Vasai' 'Godabhaga'
 'Kantabaji' 'Nimapara' 'Chogawan' 'Jaitu(Bajakhana)'
 'Ludhiana(Mandi gill Road)' 'Bandikui' 'Bansoor' 'Madathukulam' 'Palani'
 'Vemulawada' 'Gadwal(Lezza)' 'Devarkonda(Dindi)'
 'Huzumnagar(Garidepally)' 'Voligonda' 'Hasanpur' 'Mehrauni' 'Lediyari'
 'Nanakmatta' 'Aarah' 'Jainagar' 'Mansa' 'Malpur' 'Madikeri'
 'Maloor VFPCK' 'Pattiyam  VFPCK' 'Jaithari' 'Kotma' 'Multai' 'Damoh'
 'Datia' 'Guna' 'Gautampura' 'Biaora' 'Deori' 'Shahagarh' 'Niwadi'
 'Ujjain' 'Armori' 'Mangaon' 'Kasinagar' 'Phillaur' 'Sikar' 'Tirunelvali'
 'Charla' 'Enkoor' 'Sattupalli' 'Alampur' 'Dubbak' 'Aler'
 'Devarkonda(Mallepalli)' 'Huzurnagar' 'Kadaura']

Unique values in 'Commodity':
['Banana' 'Green Chilli' 'Pumpkin' 'Tomato' 'Ginger(Green)' 'Brinjal'
 'Bhindi(Ladies Finger)' 'Cabbage' 'Capsicum' 'Lemon' 'Red Gram' 'Onion'
 'Paddy(Dhan)(Common)' 'Maize' 'Apple' 'Bitter gourd' 'Coriander(Leaves)'
 'Corriander seed' 'Garlic' 'Guava' 'Methi(Leaves)'
 'Pointed gourd (Parval)' 'Pomegranate' 'Potato' 'Ridgeguard(Tori)' 'Yam'
 'Millets' 'Beans' 'Bottle gourd' 'Amaranthus'
 'Guar Seed(Cluster Beans Seed)' 'Same/Savi' 'Wheat' 'Cotton'
 'Sesamum(Sesame,Gingelly,Til)' 'Soyabean' 'Banana - Green'
 'Mousambi(Sweet Lime)' 'Rice' 'Bajra(Pearl Millet/Cumbu)' 'Cowpea(Veg)'
 'Cucumbar(Kheera)' 'Mint(Pudina)' 'Groundnut' 'Cauliflower' 'Guar'
 'Bengal Gram(Gram)(Whole)' 'Castor Seed' 'Jowar(Sorghum)'
 'Isabgul (Psyllium)' 'Drumstick' 'Orange' 'Raddish' 'Spinach' 'Carrot'
 'Chikoos(Sapota)' 'Peas Wet' 'Tinda' 'Pear(Marasebu)' 'Tender Coconut'
 'Mango' 'French Beans (Frasbean)' 'Beetroot' 'Indian Colza(Sarson)'
 'Papaya' 'Sponge gourd' 'Pineapple' 'Walnut' 'Chilly Capsicum'
 'Thogrikai' 'Colacasia' 'Field Pea' 'Snakeguard' 'Tapioca' 'Amphophalus'
 'Little gourd (Kundru)' 'Mango (Raw-Ripe)' 'Coconut'
 'Green Gram (Moong)(Whole)' 'Elephant Yam (Suran)' 'Coconut Seed'
 'Cluster beans' 'Amla(Nelli Kai)' 'Amranthas Red' 'Grapes' 'Ashgourd'
 'Green Avare (W)' 'Chili Red' 'Coconut Oil' 'Rubber' 'Yam (Ratalu)'
 'Green Peas' 'Kabuli Chana(Chickpeas-White)' 'Marigold(Calcutta)'
 'Mustard' 'Black Gram (Urd Beans)(Whole)' 'Lime' 'Onion Green'
 'Sweet Pumpkin' 'Arhar Dal(Tur Dal)' 'Black Gram Dal (Urd Dal)'
 'Green Gram Dal (Moong Dal)' 'Arecanut(Betelnut/Supari)' 'Turnip'
 'Chow Chow' 'Fish' 'Papaya (Raw)' 'Sweet Potato' 'Water Melon'
 'Season Leaves' 'Squash(Chappal Kadoo)' 'Ginger(Dry)' 'Dhaincha'
 'Cummin Seed(Jeera)' 'Custard Apple (Sharifa)' 'Indian Beans (Seam)'
 'Knool Khol' 'Thondekai' 'Mashrooms' 'Tamarind Fruit' 'Tube Rose(Loose)'
 'Jasmine' 'Betal Leaves' 'Tube Flower' 'Rose(Local)' 'Fig(Anjura/Anjeer)'
 'Karbuja(Musk Melon)' 'Ragi (Finger Millet)' 'Pigs' 'Goat' 'Ghee' 'Wood'
 'Gur(Jaggery)' 'Leafy Vegetable' 'Paddy(Dhan)(Basmati)'
 'Lentil (Masur)(Whole)' 'Masur Dal' 'Mustard Oil'
 'Bengal Gram Dal (Chana Dal)' 'Marigold(loose)' 'Peas(Dry)'
 'Arhar (Tur/Red Gram)(Whole)' 'Pegeon Pea (Arhar Fali)' 'Lotus Sticks'
 'Round gourd' 'Sunflower' 'Black pepper' 'Cowpea (Lobia/Karamani)'
 'Coffee' 'Long Melon(Kakri)' 'Kakada' 'Barley (Jau)' 'Sugar'
 'Tamarind Seed' 'Dry Chillies' 'Ground Nut Seed' 'Peas cod'
 'Persimon(Japani Fal)' 'Seemebadnekai' 'Linseed' 'Seetapal' 'Plum'
 'Kinnow' 'Soanf' 'Rose(Loose))' 'Mahua Seed(Hippe seed)' 'Ajwan'
 'Suva (Dill Seed)' 'Methi Seeds' 'Lint' 'Pepper ungarbled' 'Jack Fruit'
 'Moath Dal' 'Kartali (Kantola)' 'White Peas' 'Ber(Zizyphus/Borehannu)'
 'White Muesli' 'Kodo Millet(Varagu)' 'Alsandikai' 'Duster Beans' 'Rajgir'
 'Jute']

Unique values in 'Variety':
['Chakkarakeli(Red)' 'Karpura' 'Green Chilly' 'Pumpkin' 'Tomato'
 'Green Ginger' 'Brinjal' 'Bhindi' 'Cabbage' 'Capsicum' 'Lemon'
 'Masuri (W-S)' 'White' 'Medium' 'Paddy' 'D.B.' 'Other' 'Paddy fine'
 'I.R. 36' 'Apple' 'Bitter Gourd' 'Coriander' 'Full Green' 'Average'
 'Guava Navalur' 'Methi' 'Pointed gourd (Parval)' 'Pomogranate' 'Local'
 'Ridgeguard(Tori)' 'Yam' '1001' 'Millets' 'I.R. 64' 'MTU-1001'
 'Paddy Coarse' 'Bottle Gourd' 'Common' 'Swarna Masuri (OLD)' 'Amaranthus'
 'Whole' 'Potato' 'Savo Others' 'A-1, Green' 'Soyabeen' 'Coarse'
 'Cowpea (Veg)' 'Cucumbar' 'Mint(Pudina)' 'Shanker 6 (B) 30mm FIne' 'G20'
 'Cauliflower' 'Gwar' 'Garlic' 'Lokwan' 'Deshi' 'Desi (Whole)' 'Caster'

In [7]:
df.describe()

              Arrival_Date      Min_Price      Max_Price    Modal_Price
count                11274   11274.000000   11274.000000   11274.000000
mean   2024-10-25 00:00:00    4925.982394    5673.444135    5515.991921
min    2024-10-25 00:00:00       0.000000       0.000000       5.000000
25%    2024-10-25 00:00:00    2500.000000    3000.000000    3000.000000
50%    2024-10-25 00:00:00    4000.000000    4450.000000    4200.000000
75%    2024-10-25 00:00:00    5500.000000    6000.000000    6000.000000
max    2024-10-25 00:00:00  198000.000000  198080.000000  198040.000000
std                    NaN    5282.789940    5879.686480    5703.219799

In [8]:
df.isnull().sum()

State           0
District        0
Market          0
Commodity       0
Variety         0
Grade           0
Arrival_Date    0
Min_Price       0
Max_Price       0
Modal_Price     0
dtype: int64

In [9]:
df.sort_values(by='Arrival_Date', inplace=True)

In [10]:
def outlier_filter(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

In [11]:
# Apply outlier filtering for all price columns and store the result back into df
df_filtered = outlier_filter(df, 'Min_Price')
df_filtered = outlier_filter(df_filtered, 'Max_Price')
df_filtered = outlier_filter(df_filtered, 'Modal_Price')

In [12]:
df_encoded = df_filtered.copy()

In [13]:
categorical_columns = ['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade']

In [14]:
label_encoders = {}
for column in categorical_columns:
    le = LabelEncoder()
    df_encoded[column] = le.fit_transform(df_encoded[column])
    label_encoders[column] = le

In [15]:
X = df_encoded.drop(columns=['Modal_Price', 'Arrival_Date'])  # Features (excluding target and date)
y = df_encoded['Modal_Price']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
X_train.head()

      State  District  Market  Commodity  Variety  Grade  Min_Price  Max_Price
2084     21       182     193         57      112      0     4300.0     4500.0
9181      6       143     287         22      191      0     2500.0     3000.0
8460     18       293     675         11       32      2     2500.0     2500.0
4191     19       240     413        118        0      0     3700.0     3700.0
184       6       143     288         28       62      0     5800.0     6000.0

# Random Forest Regressor

In [18]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

In [19]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [20]:
y_pred = rf_model.predict(X_test)

In [21]:
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)  # Root Mean Squared Error
r2 = r2_score(y_test, y_pred)

c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [22]:
print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R² Score: {r2}")

Mean Squared Error: 12486.705843141764
Root Mean Squared Error: 111.74392978207705
R² Score: 0.9962960756680224

# Hypertuned Random Forest

In [23]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

In [24]:
rf = RandomForestRegressor(random_state=42)

In [25]:
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2, scoring='neg_mean_squared_error')

In [26]:
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 324 candidates, totalling 972 fits

c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
324 fits failed out of a total of 972.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
141 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
183 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [            nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -42000.52844785
 -39778.50610234 -40257.12414321 -44506.17795405 -41776.46192985
 -42339.30782583 -45184.69657893 -43092.15342856 -43681.85652829
 -46351.44303056 -43518.50291676 -43560.65972895 -46049.05416231
 -43575.62974787 -44129.18186565 -47319.26870217 -45481.35368412
 -45560.52284055 -51163.91173912 -48676.2920192  -48645.79480638
 -51163.91173912 -48676.2920192  -48645.79480638 -52088.74627504
 -48605.14341391 -48737.22119174 -25577.79350051 -25805.77764299
 -25906.67792194 -27697.91084064 -27385.94353578 -27222.0917891
 -29033.33325547 -28149.12280338 -28500.12441061 -28287.41932367
 -28204.19047194 -28286.36284029 -29019.16480829 -28275.34794623
 -28322.75413193 -30461.53204507 -29611.48759872 -29770.31711116
 -33614.57325792 -32823.29367745 -32773.59258466 -33614.57325792
 -32823.29367745 -32773.59258466 -33651.93387761 -33045.05941922
 -32985.94984891             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
 -31011.9314171  -29637.13556886 -30335.9957858  -33490.31760791
 -31810.12646039 -31921.76556099 -38952.25635715 -36079.21130774
 -36227.56086184 -36862.9544482  -34764.7027975  -34837.66638061
 -36973.96855139 -35170.23355727 -35119.87498713 -41059.40797778
 -38857.59248671 -38628.82215082 -44415.36186065 -41934.800777
 -42279.26258532 -44415.36186065 -41934.800777   -42279.26258532
 -44668.6091502  -42003.56666086 -42699.8515078  -24293.84034312
 -24195.8060394  -23962.23295467 -25370.12630357 -24940.75369409
 -24907.25298285 -27879.56249889 -27035.53084789 -26929.70764123
 -26945.72549443 -26429.20367068 -26444.15876396 -27025.88636548
 -26431.37809242 -26592.71776718 -28671.56064526 -27927.55744635
 -28098.76566782 -31835.20832499 -31349.61118425 -31427.13770619
 -31835.20832499 -31349.61118425 -31427.13770619 -32125.90593599
 -31696.11143386 -31550.68479948             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan -31615.98939956 -30274.45455942 -30569.88998553
 -33135.95095195 -31633.40387597 -31842.72239946 -38466.83140845
 -35899.92531617 -36193.42354473 -36217.28704443 -34521.9392205
 -34660.72520603 -36760.55643399 -35106.92033341 -35039.48122989
 -40972.89928018 -38757.65274186 -38536.45756937 -44442.60203209
 -41931.04680362 -42302.08413526 -44442.60203209 -41931.04680362
 -42302.08413526 -44643.62809698 -42042.54005633 -42694.0424651
 -24316.98809636 -23928.05075322 -23850.23273005 -25203.93080882
 -24910.26011523 -24863.96343793 -27744.38228475 -26989.99657411
 -26867.51526464 -26861.3858172  -26313.94663386 -26335.19789036
 -27061.71199743 -26367.06830489 -26564.596991   -28686.26527967
 -27914.5834818  -28089.92956856 -31835.20832499 -31362.1411613
 -31434.55623771 -31835.20832499 -31362.1411613  -31434.55623771
 -32166.3466321  -31718.16854802 -31565.96714878             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan -31554.13497465 -30240.80003047
 -30548.20458803 -33135.95095195 -31633.40387597 -31842.72239946
 -38466.83140845 -35899.92531617 -36193.42354473 -36217.28704443
 -34521.9392205  -34660.72520603 -36760.55643399 -35106.92033341
 -35039.48122989 -40972.89928018 -38757.65274186 -38536.45756937
 -44442.60203209 -41931.04680362 -42302.08413526 -44442.60203209
 -41931.04680362 -42302.08413526 -44643.62809698 -42042.54005633
 -42694.0424651  -24316.98809636 -23928.05075322 -23850.23273005
 -25203.93080882 -24910.26011523 -24863.96343793 -27744.38228475
 -26989.99657411 -26867.51526464 -26861.3858172  -26313.94663386
 -26335.19789036 -27061.71199743 -26367.06830489 -26564.596991
 -28686.26527967 -27914.5834818  -28089.92956856 -31835.20832499
 -31362.1411613  -31434.55623771 -31835.20832499 -31362.1411613
 -31434.55623771 -32166.3466321  -31718.16854802 -31565.96714878]
  warnings.warn(

GridSearchCV(cv=3, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [10, 20, 30, None],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='neg_mean_squared_error', verbose=2)

In [27]:
best_params = grid_search.best_params_
print("Best Hyperparameters: ", best_params)

Best Hyperparameters:  {'max_depth': 30, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}

In [28]:
best_rf_model = grid_search.best_estimator_

In [29]:
y_pred_best = best_rf_model.predict(X_test)

In [30]:
mse_best = mean_squared_error(y_test, y_pred_best)
rmse_best = mean_squared_error(y_test, y_pred_best, squared=False)
r2_best = r2_score(y_test, y_pred_best)

c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [31]:
print(f"Best Mean Squared Error: {mse_best}")
print(f"Best Root Mean Squared Error: {rmse_best}")
print(f"Best R² Score: {r2_best}")

Best Mean Squared Error: 11910.029000338684
Best Root Mean Squared Error: 109.1330793130052
Best R² Score: 0.9964671349863549

# XGBoost

In [32]:
xgb_model = XGBRegressor(n_estimators=300, learning_rate=0.1, max_depth=10, random_state=42)

In [33]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=300, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [34]:
y_pred_xgb = xgb_model.predict(X_test)

In [35]:
mse_xgb = mean_squared_error(y_test, y_pred_xgb)
rmse_xgb = mean_squared_error(y_test, y_pred_xgb, squared=False)  # Root Mean Squared Error
r2_xgb = r2_score(y_test, y_pred_xgb)

c:\Manasi\NMIMS\Manasi\Capstone Project\Agriculture\Bhoomi\venv\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [36]:
print(f"XGBoost Mean Squared Error: {mse_xgb}")
print(f"XGBoost Root Mean Squared Error: {rmse_xgb}")
print(f"XGBoost R² Score: {r2_xgb}")

XGBoost Mean Squared Error: 11190.599180894145
XGBoost Root Mean Squared Error: 105.78562842321325
XGBoost R² Score: 0.9966805390375806

# Hypertuned XGBoost

In [37]:
param_grid_xgb = {
    'n_estimators': [100, 300, 500],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [5, 10, 15],
    'min_child_weight': [1, 3, 5],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0]
}

In [38]:
xgb = XGBRegressor(random_state=42)

In [39]:
grid_search_xgb = GridSearchCV(estimator=xgb, param_grid=param_grid_xgb, cv=3, n_jobs=-1, verbose=2, scoring='neg_mean_squared_error')

In [ ]:
grid_search_xgb.fit(X_train, y_train)

Fitting 3 folds for each of 729 candidates, totalling 2187 fits

In [ ]:
best_params_xgb = grid_search_xgb.best_params_
print("Best Hyperparameters for XGBoost: ", best_params_xgb)

In [ ]:
best_xgb_model = grid_search_xgb.best_estimator_

In [ ]:
y_pred_best_xgb = best_xgb_model.predict(X_test)

In [ ]:
mse_best_xgb = mean_squared_error(y_test, y_pred_best_xgb)
rmse_best_xgb = mean_squared_error(y_test, y_pred_best_xgb, squared=False)
r2_best_xgb = r2_score(y_test, y_pred_best_xgb)

In [ ]:
print(f"Best XGBoost Mean Squared Error: {mse_best_xgb}")
print(f"Best XGBoost Root Mean Squared Error: {rmse_best_xgb}")
print(f"Best XGBoost R² Score: {r2_best_xgb}")

# Save the model

In [ ]:
joblib.dump(best_xgb_model, 'xgboost_model.pkl')